name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            build-ext: .exe
            artifact-ext: -x86_64-pc-windows-msvc.exe
          - target: x86_64-apple-darwin
            os: macos-latest
            build-ext: ""
            artifact-ext: -x86_64-apple-darwin
          - target: aarch64-apple-darwin
            os: macos-latest
            build-ext: ""
            artifact-ext: -aarch64-apple-darwin
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            build-ext: ""
            artifact-ext: -x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04-arm
            build-ext: ""
            artifact-ext: -aarch64-unknown-linux-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@0b1efabc08b657293548b77fb76cc02d26091c7e # Most recent commit on 2025-12-06
        with:
          targets: ${{ matrix.target }}
          toolchain: stable

      - name: Set up Rust cache
        uses: swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          key: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary and output artifact name (Windows)
        if: matrix.os == 'windows-latest'
        id: rename_win
        shell: pwsh
        run: |
          $PACKAGE_NAME = (cargo metadata --no-deps --format-version 1 | ConvertFrom-Json).packages[0].name
          $ARTIFACT_NAME = "$PACKAGE_NAME${{ matrix.artifact-ext }}"
          Move-Item "target\${{ matrix.target }}\release\$PACKAGE_NAME${{ matrix.build-ext }}" $ARTIFACT_NAME
          echo "artifact_name=$ARTIFACT_NAME" >> $env:GITHUB_OUTPUT

      - name: Rename binary and output artifact name (Unix)
        if: matrix.os != 'windows-latest'
        id: rename_unix
        shell: bash
        run: |
          PACKAGE_NAME=$(cargo metadata --no-deps --format-version 1 | jq -r ".packages[0].name")
          ARTIFACT_NAME="${PACKAGE_NAME}${{ matrix.artifact-ext }}"
          mv "target/${{ matrix.target }}/release/${PACKAGE_NAME}${{ matrix.build-ext }}" "$ARTIFACT_NAME"
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ steps.rename_win.outputs.artifact_name || steps.rename_unix.outputs.artifact_name }}
          path: ${{ steps.rename_win.outputs.artifact_name || steps.rename_unix.outputs.artifact_name }}
          compression-level: 0
